name: Generate Commit Trajectory

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 0 点自动运行
  workflow_dispatch:      # 手动触发

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取仓库
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ 生成提交轨迹 SVG
      - name: Generate commit trajectory SVG
        run: |
          mkdir -p dist
          curl -L "https://github-readme-commit-trajectory.vercel.app/api?username=Shr1mpTop" -o dist/commit-trajectory.svg

      # 3️⃣ 部署到 GitHub Pages（可指定分支）
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages   # 或者 output，根据你 Pages 设置
