import os
import requests

# 获取贡献数据
username = os.getenv('GITHUB_USERNAME')
url = f"https://github-contributions-api.deno.dev/{username}.json"
response = requests.get(url)
contributions = response.json()

# 解析贡献数据
grid_data = []
week = []

if 'contributions' in contributions:
    contribution_list = contributions['contributions']
else:
    contribution_list = contributions

for item in contribution_list:
    if isinstance(item, dict) and 'count' in item:
        count = item['count']
    elif isinstance(item, list) and len(item) > 0 and isinstance(item[0], dict) and 'count' in item[0]:
        count = item[0]['count']
    else:
        count = 0
    
    count = min(4, max(0, count))  # 映射到 0-4
    week.append(count)
    
    if len(week) == 7:
        grid_data.append(week)
        week = []

# 处理最后一周的剩余天数
if len(week) > 0:
    while len(week) < 7:
        week.append(0)
    grid_data.append(week)

# 定义颜色
colors = [
    "#f8f9fa",  # 0贡献
    "#a8e6cf",  # 1
    "#dcedc1",  # 2
    "#ffaaa5",  # 3
    "#ff8b94"   # 4+
]

# SVG 参数
pixel_size = 12
rows = 7
cols = len(grid_data)
svg_width = cols * pixel_size
svg_height = rows * pixel_size

# 生成 SVG
svg_content = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{svg_width}" height="{svg_height}">']

for x, week in enumerate(grid_data):
    for y, count in enumerate(week):
        color = colors[count]
        rect = f'<rect x="{x*pixel_size}" y="{y*pixel_size}" width="{pixel_size}" height="{pixel_size}" fill="{color}" stroke="#eaeaea" stroke-width="1"/>'
        svg_content.append(rect)

svg_content.append("</svg>")

# 保存文件
os.makedirs("dist", exist_ok=True)
with open("dist/contribution-grid.svg", "w") as f:
    f.write("\n".join(svg_content))
